/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", "Welcome to the Brain Games!");
    }

    @Test
    public void testIsPrime() {
        assertThat(Utils.isPrime(-1)).isFalse();
        assertThat(Utils.isPrime(0)).isFalse();
        assertThat(Utils.isPrime(1)).isFalse();
        assertThat(Utils.isPrime(2)).isTrue();
        assertThat(Utils.isPrime(3)).isTrue();
        assertThat(Utils.isPrime(4)).isFalse();
        assertThat(Utils.isPrime(5)).isTrue();
        assertThat(Utils.isPrime(109)).isTrue();
        assertThat(Utils.isPrime(110)).isFalse();
    }

    @Test
    void testGCD() {
        int result1 = Utils.gcd(1, 33);
        assertThat(result1).isEqualTo(1);

        int result2 = Utils.gcd(5, 7);
        assertThat(result2).isEqualTo(1);

        int result3 = Utils.gcd(5, 7);
        assertThat(result3).isEqualTo(1);

        int result4 = Utils.gcd(0, 3);
        assertThat(result4).isEqualTo(3);

        int result5 = Utils.gcd(4, 0);
        assertThat(result5).isEqualTo(4);

        int result6 = Utils.gcd(6, 9);
        assertThat(result6).isEqualTo(3);
    }
    @Test
    public void testIsInArray() {
        int[] arr = {1, 2, 3, 4, 5, 6};
        assertThat(Utils.isInArray(1,arr)).isTrue();
        assertThat(Utils.isInArray(2,arr)).isTrue();
        assertThat(Utils.isInArray(4,arr)).isTrue();
        assertThat(Utils.isInArray(6,arr)).isTrue();
        assertThat(Utils.isInArray(-1,arr)).isFalse();
        assertThat(Utils.isInArray(0,arr)).isFalse();
        assertThat(Utils.isInArray(7,arr)).isFalse();
    }
}
