/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.Scanner;

@SuppressWarnings("checkstyle:JavadocStyle")
public class App {

    public static void main(String[] args) {
        int choiceItem = choiceGame();
        System.out.println("Welcome to the Brain Games!");
        String user = Cli.dialogMethod();

        switch (choiceItem) {
            case 1:
                System.out.println("No game");
                break;
            case 2:
                GameEven.startEvenGame(user);
                break;
            case 0:
                System.out.println("Bye!");
                break;
            default:
                break;
        }
    }
    /**
     * Выбор игры.
     * @return - возвращает идентификатор выбранного меню
     */
    private static int choiceGame() {
        int choiceItem;
        String mainMenu = "Please enter the game number and press Enter.\n"
                + "1 - Greet\n"
                + "2 - Even\n"
                + "0 - Exit";
        int[] mainMenuIds = {1, 2, 0};
        System.out.println(mainMenu);
        Scanner inChoiceGame = new Scanner(System.in);
        while (true) {
            System.out.print("Your choice: ");
            choiceItem = inChoiceGame.nextInt();
            if (Utils.isInArray(choiceItem, mainMenuIds)) {
                break;
            }
            System.out.println("Wrong number. Try again!");
        }
        return choiceItem;
    }
}
